- name: Unarchive and Install prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: Copy Prometheus Service
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Copy Prometheus file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus-{{ prometheus_version }}.linux-amd64/prometheus.yml

- name: Copy Alerts file
  ansible.builtin.template:
    src: alerts.yml
    dest: /opt/prometheus-{{ prometheus_version }}.linux-amd64/alerts.yml

- name: Start Service Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Wait For Prometheus Port
  ansible.builtin.shell: sleep ; netstat -lntp | grep 9090

- name: Install Grafana
  ansible.builtin.shell: yum install -y https://dl.grafana.com/enterprise/release/grafana-enterprise-11.2.0-1.x86_64.rpm

- name: Start Service Grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
    enabled: yes

- name: Unarchive and Install Alert Manager
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v{{alert_manager}}/alertmanager-{{alert_manager}}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: Copy Alert Manager file
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager-{{alert_manager}}.linux-amd64/alertmanager.yml

- name: Copy Alert Manager Service
  ansible.builtin.template:
    src: alertmanager.service
    dest: /etc/systemd/system/alertmanager.service

- name: Start Service Alert Manager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Wait For Alert Manager Port
  ansible.builtin.shell: sleep ; netstat -lntp | grep 9093