- name: Unarchive and Install prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: Copy Prometheus Service
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Copy Prometheus file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus-2.54.1.linux-amd64/prometheus.yml

- name: Start Service Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Install Grafana
  ansible.builtin.dnf:
    name: https://dl.grafana.com/enterprise/release/grafana-enterprise-11.2.0-1.x86_64.rpm
    state: installed

- name: Start Service Grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
    enabled: yes

